apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://github.com/jesse-gonzalez/simple-rsvp-app"
    - "--destination=ntnxdemo/rsvp"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: image-pull-secret
      items:
        - key: .dockerconfigjson
          path: config.json